functionsDirectory = "C:\\Users\\Chris\\Desktop\\WEBSITES\\12. Harrison Finance\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\Chris\\Desktop\\WEBSITES\\12. Harrison Finance\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "C:\\Users\\Chris\\Desktop\\WEBSITES\\12. Harrison Finance\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]